-- Remove existing companions
DELETE FROM companions;

-- Insert new demo companions
INSERT INTO companions (
  id,
  name,
  description,
  state,
  city,
  neighborhood,
  whatsapp,
  services,
  service_for,
  service_locations,
  ethnicity,
  nationality,
  breast_type,
  hair_color,
  body_type,
  availability,
  is_verified,
  is_premium,
  created_at,
  price,
  rating,
  reviews,
  imageUrl
) VALUES 
(
  'comp-001',
  'Isabella Santos',
  'Olá! Sou uma acompanhante de luxo com experiência em proporcionar momentos únicos e inesquecíveis.',
  'São Paulo',
  'São Paulo',
  'Jardins',
  '11999999999',
  ARRAY['Massagem erótica', 'Massagem tântrica', 'Beijo francês'],
  ARRAY['Homens', 'Casais'],
  ARRAY['Hotel / Motel', 'Em casa'],
  'Latina',
  'Brasileira',
  'Seios Natural',
  'Cabelo Castanho',
  'Curvas',
  '{"Segunda": {"start": "10:00", "end": "22:00"}, "Terça": {"start": "10:00", "end": "22:00"}, "Quarta": {"start": "10:00", "end": "22:00"}, "Quinta": {"start": "10:00", "end": "22:00"}, "Sexta": {"start": "10:00", "end": "22:00"}, "Sábado": {"start": "12:00", "end": "20:00"}, "Domingo": {"start": "12:00", "end": "20:00"}}',
  true,
  true,
  NOW(),
  300,
  4.8,
  124,
  'https://example.com/photos/isabella.jpg'
),
(
  'comp-002',
  'Julia Oliveira',
  'Acompanhante de alto nível, discreta e elegante. Atendimento personalizado para momentos especiais.',
  'Rio de Janeiro',
  'Rio de Janeiro',
  'Copacabana',
  '21999999999',
  ARRAY['Massagem erótica', 'Beijo francês', 'Tratamento de namorados'],
  ARRAY['Homens'],
  ARRAY['Hotel / Motel'],
  'Brasileiras',
  'Brasileira',
  'Com silicone',
  'Cabelo Loiro',
  'Magra',
  '{"Segunda": {"start": "14:00", "end": "23:00"}, "Terça": {"start": "14:00", "end": "23:00"}, "Quarta": {"start": "14:00", "end": "23:00"}, "Quinta": {"start": "14:00", "end": "23:00"}, "Sexta": {"start": "14:00", "end": "23:00"}, "Sábado": {"start": "16:00", "end": "23:00"}}',
  true,
  false,
  NOW(),
  250,
  4.5,
  89,
  'https://example.com/photos/julia.jpg'
),
(
  'comp-003',
  'Sofia Mendes',
  'Carinhosa e sensual, proporciono momentos inesquecíveis com muito glamour e discrição.',
  'Minas Gerais',
  'Belo Horizonte',
  'Savassi',
  '31999999999',
  ARRAY['Oral', 'Massagem erótica', 'Beijo francês', 'Fetiches'],
  ARRAY['Homens', 'Casais', 'Mulheres'],
  ARRAY['Hotel / Motel', 'Em casa', 'Eventos e festas'],
  'Latina',
  'Brasileira',
  'Seios Natural',
  'Cabelo Preto',
  'Curvas',
  '{"Segunda": {"start": "12:00", "end": "22:00"}, "Terça": {"start": "12:00", "end": "22:00"}, "Quarta": {"start": "12:00", "end": "22:00"}, "Quinta": {"start": "12:00", "end": "22:00"}, "Sexta": {"start": "12:00", "end": "22:00"}, "Sábado": {"start": "14:00", "end": "22:00"}}',
  true,
  true,
  NOW(),
  400,
  4.9,
  156,
  'https://example.com/photos/sofia.jpg'
),
(
  'comp-004',
  'Amanda Costa',
  'Acompanhante VIP para momentos especiais. Atendimento exclusivo e personalizado.',
  'São Paulo',
  'Campinas',
  'Cambuí',
  '19999999999',
  ARRAY['Massagem tântrica', 'Beijo francês', 'Tratamento de namorados', 'Massagem erótica'],
  ARRAY['Homens', 'Casais'],
  ARRAY['Hotel / Motel', 'Em casa'],
  'Brasileiras',
  'Brasileira',
  'Com silicone',
  'Cabelo Ruivo',
  'BBW',
  '{"Segunda": {"start": "09:00", "end": "21:00"}, "Terça": {"start": "09:00", "end": "21:00"}, "Quarta": {"start": "09:00", "end": "21:00"}, "Quinta": {"start": "09:00", "end": "21:00"}, "Sexta": {"start": "09:00", "end": "21:00"}, "Sábado": {"start": "10:00", "end": "18:00"}}',
  true,
  false,
  NOW(),
  350,
  4.7,
  92,
  'https://example.com/photos/amanda.jpg'
),
(
  'comp-005',
  'Valentina Rodriguez',
  'Venezuelana fogosa, carinhosa e muito sensual. Momentos inesquecíveis garantidos.',
  'São Paulo',
  'São Paulo',
  'Moema',
  '11999999999',
  ARRAY['Oral', 'Anal', 'Beijo francês', 'Massagem erótica'],
  ARRAY['Homens'],
  ARRAY['Hotel / Motel', 'Em casa'],
  'Latina',
  'Venezuelana',
  'Com silicone',
  'Cabelo Castanho',
  'Magra',
  '{"Segunda": {"start": "11:00", "end": "23:00"}, "Terça": {"start": "11:00", "end": "23:00"}, "Quarta": {"start": "11:00", "end": "23:00"}, "Quinta": {"start": "11:00", "end": "23:00"}, "Sexta": {"start": "11:00", "end": "23:00"}, "Sábado": {"start": "13:00", "end": "21:00"}, "Domingo": {"start": "13:00", "end": "21:00"}}',
  true,
  true,
  NOW(),
  500,
  4.9,
  178,
  'https://example.com/photos/valentina.jpg'
);