-- Insert demo companions
INSERT INTO companions (
  id,
  user_id,
  name,
  email,
  phone,
  description,
  neighborhood,
  city,
  state,
  services,
  ethnicity,
  body_type,
  hair_color,
  breast_type,
  height,
  weight,
  measurements,
  is_verified,
  is_premium,
  price,
  rating,
  reviews,
  service_areas
) VALUES 
(
  'comp-001',
  null,
  'Sofia Oliveira',
  'sofia@example.com',
  '11999999999',
  'Olá! Sou a Sofia, uma acompanhante de luxo em São Paulo. Ofereço momentos únicos e inesquecíveis.',
  'Jardins',
  'São Paulo',
  'SP',
  ARRAY['Massagem tântrica', 'Jantar', 'Pernoite', 'Viagens'],
  'Latina',
  'Curvas',
  'Cabelo Castanho',
  'Natural',
  165,
  55,
  '90-60-90',
  true,
  true,
  300,
  4.8,
  124,
  ARRAY['Jardins', 'Pinheiros', 'Vila Madalena', 'Itaim Bibi']
),
(
  'comp-002',
  null,
  'Julia Santos',
  'julia@example.com',
  '21999999999',
  'Julia, acompanhante de alto nível no Rio de Janeiro. Momentos de prazer e diversão garantidos.',
  'Copacabana',
  'Rio de Janeiro',
  'RJ',
  ARRAY['Massagem relaxante', 'Jantar', 'Eventos', 'Viagens'],
  'Brasileira',
  'Magra',
  'Cabelo Loiro',
  'Silicone',
  170,
  58,
  '88-62-92',
  true,
  false,
  250,
  4.5,
  89,
  ARRAY['Copacabana', 'Ipanema', 'Leblon', 'Barra da Tijuca']
);

-- Add companion photos
INSERT INTO companion_photos (companion_id, url, is_primary) VALUES
('comp-001', '/demo/sofia1.jpg', true),
('comp-001', '/demo/sofia2.jpg', false),
('comp-001', '/demo/sofia3.jpg', false),
('comp-002', '/demo/julia1.jpg', true),
('comp-002', '/demo/julia2.jpg', false),
('comp-002', '/demo/julia3.jpg', false);